name: Cypress Tests using GitHub Runners

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          command: npx cypress run --browser ${{ matrix.browser }} --reporter --reporter options reportDir=cypress/reports/${{ matrix.browser }}

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/${{ matrix.browser }}/*.json > cypress/reports/${{ matrix.browser }}/merged-reports.json
      
      - name: Generate HTML reports
        run: npx merge cypress/reports/${{ matrix.browser }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browser }} -f "${{ matrix.browser }}--report.html"

      - name: upload html Reports
        uses: actions/upload-artifact@v4
        with:
            name: Cypress HTML Report ${{ matrix.browser }}
            path: cypress/reports/${{ matrix.browser }}




